### ISSUE TITLE
As a DOI user, I would like to know the licensing information PDS data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#224]
## Motivation
...so that I can ensure sufficient licensing information is included in the DOI metadata and I know how I am allowed to use PDS data.

## Additional Details

Licensing should be CC0

Example TBD from SBN

### AC1: New DOI
**Given** a data set requiring a new DOI
**When I perform** the steps to create a DOI
**Then I expect** CC0 licensing info to included in the DOI metadata submitted to DataCite

### AC2: Update existing DOI
**Given** an existing DOI that was created prior to this ticket creation
**When I perform** a query for the DOI
**Then I expect** CC0 licensing info has been updated and included in the DOI metadata

## Engineering Details

**UPDATE FROM SMD AS OF 11/18/2021**
PDS data should be licensed under CC0 unless otherwise specified.

**Comment by jordanpadams** [comment]
deferring until later date. not super critical at this time.

**Comment by alexdunnjpl** [comment]
Behaviour as-implemented:

 - new DOIs get GWorks and CC0 by default
 - `release` applied with no `rightsList` attribute present in label data gets GWorks and CC0
 - `release` applied with empty or other-valued `rightsList` attribute in label data gets whatever the label specifies.
