### ISSUE TITLE
Add licensing information to DOI metadata for new DOIs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#225]
See parent story for details on the licensing information to include

**Comment by jordanpadams** [comment]
deferring for now. not super critical.

**Comment by alexdunnjpl** [comment]
Behaviour as-implemented:

 - new DOIs get GWorks and CC0 by default
 - `release` applied with no `rightsList` attribute present in label data gets GWorks and CC0
 - `release` applied with empty or other-valued `rightsList` attribute in label data gets whatever the label specifies.
