### ISSUE TITLE
Improve upon application security for write access

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#231]
## Motivation
#228 is a weak security measure for ensuring secure access. this ticket is to improve upon that security strategy.

**Comment by tloubrieu-jpl** [comment]
The usage of oauth will be considered for the future.

Just for now, we will try to have the same basic authentication on the UI and on the API reverse proxy in apache and see how that works.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams this ticket can be cancelled since the solution for the UI and API authentication is BasicAuthentication with a single login password which is technically ok regarding security. The only concern is that the password is shared in between different individuals.

In addition having individual login password could help for the personalization of the UI

But we will not upgrade this setting until we'll have a central directory for the PDS partners which is another story.

**Comment by tloubrieu-jpl** [comment]
If not duplicate we can have this ticket in icebox

**Comment by jordanpadams** [comment]
This solution has been fixed by basic auth as described above. See wiki to verify the application security is sufficiently documented in the deployment documentation.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can you provide a link to the appropriate deployment docs where this is described?

**Comment by tloubrieu-jpl** [comment]
No problem @jordanpadams 

The docs for the DOI deployment can be found on the internal JPL wiki https://wiki.jpl.nasa.gov/display/PDSEN/DOI+Services
