### ISSUE TITLE
Develop script to sync DOIs with legacy registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#248]
## Engineering Details
This should be a script that can be run as a cronjob to:

- [ ] sync the DOIs from our DOI service database to the applicable products in the legacy registry

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is the legacy registry the registry in production now (before the deployment that Jimmie is working on ?)

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @collinss-jpl it is the registry that drives this: https://pds.nasa.gov/services/search/search?wt=json&q=*:* which drives this: https://pds.nasa.gov/datasearch/keyword-search/ 

now that I think about it though, I think we will not be able to use this service to do this. the registry re-indexes everything every time there is a new release, so it will lose those DOIs as soon as there is another data release. we should just update the new registry, and our landing pages can just query the new registry for the DOIs

**Comment by tloubrieu-jpl** [comment]
Ok, thanks @jordanpadams that makes that ticket easier !
