### ISSUE TITLE
Develop script to sync DOIs to registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#249]
## ⚙️ Engineering Details

This should be a script that can be run as a cronjob to:
- [x] discuss with @tdddblog what is the best approach for bulk updates to the registry (or this ability may already exist?)?
- [x] sync the DOIs from our DOI service database to the applicable products in the registry

**Comment by tloubrieu-jpl** [comment]
@tdddblog says the bulk update is supported by elasticsearch

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can we table that for this build ? I remember there was question on how we manage the consistency of the original label with the registry content.
In addition, without Scott is becomes challenging to have that done by the end of the sprint.

**Comment by tloubrieu-jpl** [comment]
We can use registry manager supplementer to work on that.

1. First step will be to extract from identifier and doi from the sqllite database as a CSV.
2. Second step will be to use this output as a supplemental metadata label, to update the registry

**Comment by tloubrieu-jpl** [comment]
This ticket has been closed per PR https://github.com/NASA-PDS/supplementer/pull/8
