### ISSUE TITLE
Update all past DOIs for consistent metadata

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#294]
## 💪 Motivation
...so that I can easily correlate all DOIs together

## 📖 Additional Details

Some of the older DOIs have invalid metadata. We want to make this consistent

- [x] #303
- [x] Update bad contributors ([bad_contributors.txt](https://github.com/NASA-PDS/pds-doi-service/files/7515697/bad_contributors.txt))
- [x] Update publishers to all be `NASA Planetary Data System`
- [x] Update node contributor names:
   - [x] Radio Science Node -> Planetary Data System: Radio Science Node
   - [x] Geosciences Node -> Planetary Data System: Geosciences Node
   - [x] Ring-Moon Systems Node -> Planetary Data System: Ring-Moon Systems Node
- [X] ~Fix missing creators ([bad_creators.txt](https://github.com/NASA-PDS/pds-doi-service/files/7515761/bad_creators.txt))~
- [x] Update resourceType
   - [x] PDS4 Collection -> PDS4 Refereed Data Collection
   - [x] PDS4 Bundle -> PDS4 Refereed Data Bundle
   - [x] PDS3 DataSet Catalog -> PDS3 Refereed Data Set
   - [x] PDS4 Document -> PDS4 Refereed Document

I think the tasks below have been deprecated per #303 

> 
> - [ ] PDS3 DOIs have inconsistent URNs in the metadata
>    * Some use the PDS3 Data Set ID, e.g. [10.17189/1521151](https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.17189/1521151)
> ```json
>   "identifiers": [
>     {
>       "identifier": "1521151",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "relatedIdentifierType": "URN"
>     }
>   ],
> ```
>    * others use the PDS4 registry identifier, e.g. [10.17189/1519454](https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.17189/1519454)
> ```json
>   "identifiers": [
>     {
>       "identifier": "1519454",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "A14A-L-CCIG-3-ATMOS-DENSITY-PLOTS-V1.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "urn:nasa:pds:context_pds3:data_set:data_set.a14a-l-ccig-3-atmos-density-plots-v1.0",
>       "relatedIdentifierType": "URN"
>     }
>   ],
> ```
> - [ ] updating all these PDS3 DOIs to use the data set ID as `Handle` and generate the URN from the data set ID as the URN, so for example, these 2 different use cases from above:
> 1.
> ```json
>   "identifiers": [
>     {
>       "identifier": "1521151",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "relatedIdentifierType": "URN"
>     }
>   ],
> ```
> becomes
> ```json
>   "identifiers": [
>     {
>       "identifier": "1521151",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "CO-E/SW/J/S-MAG-3-RDR-FULL-RES-V2.0",
>       "relatedIdentifierType": "Handle"
>     }
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "urn:nasa:pds:context_pds3:data_set:data_set.co-e-sw-j-s-mag-3-rdr-full-res-v2.0",
>       "relatedIdentifierType": "Handle"
>     }
>   ],
> ```
> **Note: To create the URN, you will need to convert `/` to `-`.
> 
> 2.
> ```json
>   "identifiers": [
>     {
>       "identifier": "1519454",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "A14A-L-CCIG-3-ATMOS-DENSITY-PLOTS-V1.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "urn:nasa:pds:context_pds3:data_set:data_set.a14a-l-ccig-3-atmos-density-plots-v1.0",
>       "relatedIdentifierType": "URN"
>     }
>   ],
> ```
> becomes this:
> ```json
>   "identifiers": [
>     {
>       "identifier": "1519454",
>       "identifierType": "IAD ID"
>     },
>     {
>       "identifier": "A14A-L-CCIG-3-ATMOS-DENSITY-PLOTS-V1.0",
>       "identifierType": "Site ID"
>     }
>   ],
>   "relatedIdentifiers": [
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "A14A-L-CCIG-3-ATMOS-DENSITY-PLOTS-V1.0",
>       "relatedIdentifierType": "URN"
>     }
>     {
>       "relationType": "IsIdenticalTo",
>       "relatedIdentifier": "urn:nasa:pds:context_pds3:data_set:data_set.a14a-l-ccig-3-atmos-density-plots-v1.0",
>       "relatedIdentifierType": "URN"
>     }
>   ],
> ```

**Comment by tloubrieu-jpl** [comment]
The result of this ticket should be the work done + a re-usable documentation for next similar cases.

**Comment by jordanpadams** [comment]
spot checked a few DOIs and this looks good to go
