### ISSUE TITLE
Document need to be update after adding the update argument

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/doi-service#313]
## 🐛 Describe the bug identified during I&T
It is not clear how to use the new --update argument. 
It is not in https://nasa-pds.github.io/doi-service/usage/index.html
and --help doesn't provide usage instructions.

positional arguments:
  {reserve,update,release,check,list}

These two lines does not help.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl while you update the documentation can you make sure it is clear to the user that the --help option works also subcommand, for example `pds-doi-cmd reserve --help`

Thanks
