### ISSUE TITLE
Add Radio Science to set of possible nodes

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#317]
## 💡 Description

Radio Science Sub-node is a new node. Add to set of possible acronyms.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can you identify where the node is missing, because @collinss-jpl checked and it is supported by the tool and show as an option when one use the --help option.

**Comment by collinss-jpl** [comment]
For reference, here is where RS node was added so it shows up as an option for our `--node` arguments:

https://github.com/NASA-PDS/doi-service/blob/main/src/pds_doi_service/core/util/node_util.py#L26

**Comment by jordanpadams** [comment]
thanks @collinss-jpl 

@rsjoyner can you please confirm?

**Comment by tloubrieu-jpl** [comment]
@rsjoyner confirmed in an email
