### ISSUE TITLE
Corruption in local database with invalid JSON

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#318]
## 🐛 Describe the bug

When trying to list all DOIs in the database, we are getting an error

## 📜 To Reproduce
```
pds-doi-cmd list -start 1990-01-01 -end 2022-02-15 -f label > DataCite_dump_results_20220215.json
...
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 82 column 320 (char 3528)
```

## 🕵️ Expected behavior

Able to execute the pds-doi-cmd command above successfully.

## ⚙️ Engineering Details
per @collinss-jpl 
> Somehow, an invalid JSON label found its way into the transaction database, and unfortunately it’s not clear exactly which label it is. Some debug statements need to be added to print the DOI/PDS ID prior to parsing of each label by the list action. Or conversely, the current database/transaction history on prod1 could be deleted and resynced from DataCite.

I think our easiest solution to get this fixed is the latter:
> the current database/transaction history on prod1 could be deleted and resynced from DataCite.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @rsjoyner the corrupted label prefix is 10.26033.

Who is authoring these labels ?

I will go on looking at which exact label triggers the error and I'll let you know.

**Comment by tloubrieu-jpl** [comment]
It is from small bodies node, the DOI is 10.26033/q9qr-cn93

**Comment by tloubrieu-jpl** [comment]
email sent to @jordanpadams and @rsjoyner today. We need to contact someone at SBN to do the update.

**Comment by jordanpadams** [comment]
forwarded to SBN for updates

**Comment by tloubrieu-jpl** [comment]
Update has been done by SBN, @tloubrieu-jpl need to synchronize data again and retest the list command

**Comment by tloubrieu-jpl** [comment]
Synchronization is done and the `list` command works again on pds-prod1
