### ISSUE TITLE
deactivate registered cassini doi 10.17189/1517823

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#321]
## 🐛 Describe the bug

It is duplicated with [10.17189/1518302](https://doi.org/10.17189/1518302)

## 📜 To Reproduce
Go to the DOI search and search for cassini (https://pds.nasa.gov/tools/doi/#/search/cassini)

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
updated in datacite, now need to see if this will automatically sync with our database or if we need to force a sync. https://doi.datacite.org/dois/10.17189%2F1517823

**Comment by jordanpadams** [comment]
updated the metadata so it no longer appears in the search for cassini DOIs
