### ISSUE TITLE
synchronize dataCite test prefix with the production prefix

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#325]
## 💪 Motivation
...so that tester can have a more production like experience.
This also has impact on the ds-view feature which shows DOIs. So far there are not many DOIs in the test dataCite which matches the products in registry on pds-gamma.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
closing this as wontfix since I am pretty certain the database sync has been fixed to include all operational and test DOIs
