### ISSUE TITLE
doi sync failing for SBN-PSI DOIs

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/doi-service#331]
I harvested two bundles one after the other. Both have DOIs, but the search results return the right DOI for bundle_mgs-rss_nocturnal-mixed-layers.xml but "No DOI found" for bundle.xml. See
https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:nasa:pds:mgs-rss_nocturnal-mixed-layers
https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:nasa:pds:dart_teleobs

The two input xml files are attached. The main differences I see are that the "bad" file:
- has a DOI that begins with 10.26007 
- has no Context_Area/Observing_System

My question: why isn't the DOI showing up? Will this likely be resolved when #316 is resolved, or is there actually something wrong with the registry or the .xml files, or did I do something else?

I did check that Harvest parsed correctly because the registry's slot for both citation_doi has the right value. I checked by getting on pdscloud-prod2 and running firefox over X windows with URLs http://localhost:8080/registry-pds4/extrinsics?lid=urn:...
(That actually showed one more subtle difference: slot citation_keyword had a list of values for the good file but a single value for the bad one even though both .xml files had only a single value, but the good file's Citation_Information/keyword included semicolons. That is most likely irrelevant here)

[bundle.xml.txt](https://github.com/NASA-PDS/doi-service/files/8644732/bundle.xml.txt)
[bundle_mgs-rss_nocturnal-mixed-layers.xml.txt](https://github.com/NASA-PDS/doi-service/files/8644733/bundle_mgs-rss_nocturnal-mixed-layers.xml.txt)

## ⚙️ Engineering Details
* This relates to the [cronjobs discussed here](https://wiki.jpl.nasa.gov/display/PDSEN/DOI+Service+Installation+and+Deployment#DOIServiceInstallationandDeployment-Cronjob)
* Verify cronjobs are running
* If running, see logs to see error for this DOI

**Comment by jordanpadams** [comment]
@rchenatjpl those values are populated directly from the DOI service, not the registry. So if the DOIs can be found on the DOI search page, then there is a big in the ds-view query. If the DOI does not show up in the search, it means the DOI was either never registered or is not "findable".

Does that make sense?

**Comment by jordanpadams** [comment]
@rchenatjpl actually, I see that the one where the DOI does not show up is an SBN DOI. We have a Cronjob that runs regularly to go pick those up and add them to our database. If you don't see that updated by Monday, then we will have to investigate. There may be an issue with the metadata they provided for that DOI and our database.

**Comment by tbarnes4** [comment]
@jordanpadams and @rchenatjpl 

I will have to look into this, but the DOI for the SBN-UMD DART Telescopic Observation Archive is live and has been for a few weeks:  https://www.doi.org/10.26007/y02j-ma79

Now I do know that we did not fully fill out all the metadata for the DOI, only the required fields for publication of said ID.  If you look at the source of the [html landing page](https://pdssbn.astro.umd.edu/holdings/pds4-dart_teleobs-v1.0/SUPPORT/dataset.shtml), you can see that our scripts successfully pulled the registered DOI metadata.

**Comment by tbarnes4** [comment]
d

**Comment by jordanpadams** [comment]
Issue appears to be with DOI metadata and a null identifier:
```
    "identifiers": [
        {
            "identifier": "urn:nasa:pds:dart_teleobs::1.0",
            "identifierType": "PDS4 Bundle ID"
        },
        {
            "identifier": null,
            "identifierType": null
        }
    ],
```

improving software to pop of these bad values before we ingest into database
