### ISSUE TITLE
Fix broken build

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#341]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/doi-service/actions/runs/2578868398

**Comment by jordanpadams** [comment]
@nutjob4life sorry. I think I broke this when updating the pre-commit to use the new one we put on the template erpo.

**Comment by nutjob4life** [comment]
I struggled to reproduce this locally (using everything from a direct host-based build environment, a pseudo-roundup environment in the GitHub Actions Base image, as well as a full Roundup in a local container), but failed.

So I decided just to rerun the failed build directly on GitHub … and it worked!

https://github.com/NASA-PDS/doi-service/runs/7234254202?check_suite_focus=true

I think we should just close this as a one-off fluke. Call it a cosmic ray or something.

**Comment by tloubrieu-jpl** [comment]
It was not reproduced, let's close it.
