### ISSUE TITLE
Tag and deploy new release per #331

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#342]
## 💡 Description

- [x] tag 2.2.1 release (@tloubrieu-jpl)
- [x] deploy 2.2.1 on machines (@viviant100 ??? SAs? Catherine? Someone else?)

**Comment by tloubrieu-jpl** [comment]
Hi @c-suh, @viviant100 , I tagged a new release of doi-service 2.2.1. Can you deploy it on pdscloud-prod1, pdscloud-prod2 and pdscloud-gamma and let Ron know that it contains the fix for this ticket https://github.com/NASA-PDS/doi-service/issues/328

**Comment by viviant100** [comment]
@tloubrieu-jpl does this new release of doi-service 2.2.1 also require python 3.9.10+ to avoid the error I&T encountered in the previous release?

**Comment by c-suh** [comment]
@viviant100 and @tloubrieu-jpl I upgraded doi-service to 2.2.1 on pdscloud-gamma only. Let me know if I should wait or proceed. Thank you!

**Comment by viviant100** [comment]
Thanks @c-suh.  doi-service 2.2.0 errored out with python 3.9.7.   @tloubrieu-jpl can help us confirm if this is part of improvement in 2.2.1.  If not, we'll upgrade python to 3.9.10+ on pdscloud-gamma and test it before roll out to production.

**Comment by tloubrieu-jpl** [comment]
Hi @viviant100 , sorry I don't recall this issue with python 3.9.7 and doi-service 2.2.0, I don't think we have a fix for that. Is there a ticket tracking that ?

**Comment by viviant100** [comment]
@tloubrieu-jpl the error was mentioned in the ticket https://github.com/NASA-PDS/doi-service/issues/328 by Gary.

**Comment by tloubrieu-jpl** [comment]
@viviant100 I missed it earlier. We did not do any fix for that.

I've just tested the ticket #328 with my local environment having python 3.9.1 and it worked.

I suggest that we create a ticket if this happens again in production of gamma.

**Comment by viviant100** [comment]
@jordanpadams @tloubrieu-jpl doi-service 2.2.1 is now deployed to pdscloud-* and tested.  Ron is informed this version (v2.2.1) contains the fix for ticket https://github.com/NASA-PDS/doi-service/issues/328.

**Comment by jimmie** [comment]
Everything deployed and proven.
