### ISSUE TITLE
Implement COGNITO token verification in the doi-service API

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#348]
## 💡 Description

Implement the cognito token verification natively in the API so that it can verify the token on its own, without using apache for doing so (which did not work well) or adding an API gateway configuration (which adds a component to configure and document)

**Comment by ramesh-maddegoda** [comment]
Updated  authentication to verify signature of JWT tokens

**Comment by ramesh-maddegoda** [comment]
Pull request available at https://github.com/NASA-PDS/doi-service/issues/348

**Comment by ramesh-maddegoda** [comment]
@jordanpadams, I updated the code to verify signature of JWT tokens
