### ISSUE TITLE
Enhance weekly reporting to push to ADS SFTP server

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/doi-service#363]
## 💡 Description

Per discussions with ADS folks, they would prefer we deliver by SFTP. So let's add that as an additional delivery mechanism. SFTP information TBD

**Comment by alexdunnjpl** [comment]
Protocol: sFTP (SSH File Transfer Protocol)
Host: sftp.kube.adslabs.org
Port: 22
Logon: Normal (or Ask for Password if you want to type password upon logon)
Username: <provided_by_ADS>
Password: <provided_by_ADS>

**Comment by alexdunnjpl** [comment]
@jordanpadams still need

 - credentials
 - output format (json? timestamped files?)
 - sftp target dirpath

**Comment by alexdunnjpl** [comment]
sftp path: `pds` (should automatically set on login)
format: any structured (json probably best)
credentials provided

**Comment by jordanpadams** [comment]
@alexdunnjpl do we know if this is actually running operationally or not?

**Comment by alexdunnjpl** [comment]
@jordanpadams not at last touch (that I can find)

https://jpl.slack.com/archives/GCGR1R3A4/p1666042885693059

I can start it on gamma, or someone with access to prod can set it up there - it's just a matter of adding [the wrapper script](https://github.com/NASA-PDS/doi-service/blob/main/scripts/sftp_drop_weekly_roundup.py) to the crontab and [the relevant config values](https://github.com/NASA-PDS/doi-service/blob/main/scripts/sftp_drop_weekly_roundup.py#L24-L28) to the config.

**Comment by gxtchen** [comment]
@jordanpadams @alexdunnjpl How do I verify this enhancement? --Gary

**Comment by jordanpadams** [comment]
@gxtchen I think we can just smoke test this when we actually start up the script. we can skip I&T here
