### ISSUE TITLE
Deploy ADS delivery script to operations

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-service#399]
## 💡 Description

Run the script Alex created to deliver our DOI records to ADS on a weekly basis.

* See PR https://github.com/NASA-PDS/doi-service/pull/379
* Script here: https://github.com/NASA-PDS/doi-service/blob/main/scripts/sftp_drop_weekly_roundup.py

NOTE: We should discuss how we want to deploy this to fit with some of our other "cron"-like jobs. Should this be run on EC2 or using the AWS scheduler?

**Comment by c-suh** [comment]
Script is running from cron although I'm unsure of the json file contents. Am confirming with Alex.

**Comment by jordanpadams** [comment]
@c-suh as one off smoke test can you run the script manually and post the output for @alexdunnjpl and I to review?

**Comment by alexdunnjpl** [comment]
@jordanpadams how questionable is it that zero DOIs were updated in the previous calendar week?

Output checks out, apart from that.  The code is well-tested (he committed, committingly) so if that's not obviously wrong there's no issue here.

**Comment by c-suh** [comment]
@jordanpadams I ran the script by modifying the time in cron and sent the contents of the json file to Alex, which had 0 modified DOI records (like he just said). After that, I checked the sync logs. For DOIs starting with 260*, there haven't been any written for the past while (about a month, at least).
