### ISSUE TITLE
ADS SFTP drop intermittently fails when deployed in production

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/doi-service#407]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Per [@c-suh initial report](https://jpl.slack.com/archives/D05BVEP2E67/p1686592187208859)

### 🕵️ Expected behavior

Weekly Monday-at-0000h cron job should produce output on ADS SFTP server.
This output should contain correct data.

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by alexdunnjpl** [comment]
@c-suh to re-test with midnight-tonight cron, @alexdunnjpl to implement additional logging

**Comment by alexdunnjpl** [comment]
c-suh to re-try wednesday tonight - it's possible everything is already working as-expected

**Comment by alexdunnjpl** [comment]
@jordanpadams did you already send out an email asking about this, or should I contact Carolyn?

**Comment by jordanpadams** [comment]
@alexdunnjpl @c-suh just to verify, could it be we did not update/create any DOIs that week? Or do we deliver empty reports?

**Comment by alexdunnjpl** [comment]
@jordanpadams empty reports (with a consistent structure for ease of use, just with an empty array of results) are delivered, in that case.

**Comment by jordanpadams** [comment]
ok
