### ISSUE TITLE
GUI not available on pds.nasa.gov; Still not available 20230901

### ISSUE THREAD

**Issue by rsjoyner** [NASA-PDS/doi-service#412]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

As of this morning 20230901, the GUI is still not available.
   -- System error. Please contact the System Administrator.

This morning this url:  https://pds.nasa.gov/tools/doi-editor/#/create
issues error: The doi api is currently unreachable. Please check your internet connection. If you are connected and the problem persists please contact the <a href="https://pds-gamma.jpl.nasa.gov/tools/doi/?feedback=true">PDS Operator</a> for assistance.

### 🕵️ Expected behavior

I expected to be able to access the GUI via that URL
![Snap151](https://github.com/NASA-PDS/doi-service/assets/63060872/143b820b-0887-4247-8b45-2db8d43f8423)

### 📜 To Reproduce

1. enter URL
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
This was a temporary issue that I believe should be fixed now.
